### ISSUE TITLE
Youtube Music not displayed correctly?

### ISSUE THREAD

**Issue by Andoramb** [ferferga/MMM-GoogleCast#12]
Hi!

Thanks for the module, really like it.
I just observed when playing music from Youtube, it just displays the source and the default image. No artwork, no title/artist.
With Spotify it's OK. Is this known?

Thanks again

**Comment by ferferga** [comment]
@Andoramb Hello and thank you very much for your feedback! 😊

Is the image displayed correctly in the Google Home app? Because this module is more less a "viewer" of what the Google Home app sees. It depends mostly on the information that the casting app is relying to the casting framework.

**Comment by Andoramb** [comment]
Google home displays the artist and title, but not the artwork for Youtube Music (which is strange, compared to Spotify, as that works OK). I also use Home Assistant and there everything is displayed accordingly (Title, Artist, Cover, etc.)
The Mirror log gives me:
`[2020-04-15 08:55:26.258] [LOG]    [MMM-GoogleCast] Update received! Details:
 {
  mediaStatus: {
    id: 'xxxx',
    title: null,
    artist: null,
    album: null,
    albumArtist: null,
    state: 'UNKNOWN',
    image: null
  }
}`

**Comment by ferferga** [comment]
@Andoramb Hmm that's strange. Can you check which key contains the image that is displayed in Home Assistant checking it logs? This module and Home precisely take them from that JSON key.

**Comment by Andoramb** [comment]
@ferferga thanks for the quick reply :)
It's strange... sometimes it works, sometimes it displays just the default artwork, but only with Youtube. (so I cannot state that Yt has a different query or ID). 
Yes, I saw that pychromecast was developed by balloob, founder of HA :)

I'm not sure what logs to check, but I can see my media player entity's state in HA:
```<template state 
media_player.entryway_speaker=playing;
volume_level=0.4000000059604645,
is_volume_muted=False,
media_content_id=uDx4HR3o59A,  
media_content_type=music,  
media_duration=245, 
media_position=0.3, 
media_title=See The Light, 
media_artist=Ghost, 
media_album_name=Prequelle, 
app_id=2DB7CC49, 
app_name=YouTube Music, 
friendly_name=Entryway speaker, entity_picture=https://i.ytimg.com/vi/uDx4HR3o59A/hqdefault.jpg, 
supported_features=21437,

**Comment by Andoramb** [comment]
this is essentially the same anyway for Spotify or other media sources.

**Comment by ferferga** [comment]
> @ferferga thanks for the quick reply :)
> It's strange... sometimes it works, sometimes it displays just the default artwork, but only with Youtube. (so I cannot state that Yt has a different query or ID). 
> Yes, I saw that pychromecast was developed by balloob, founder of HA :)
> 
> I'm not sure what logs to check, but I can see my media player entity's state in HA:
> ```<template state 
> media_player.entryway_speaker=playing;
> volume_level=0.4000000059604645,
> is_volume_muted=False,
> media_content_id=uDx4HR3o59A,  
> media_content_type=music,  
> media_duration=245, 
> media_position=0.3, 
> media_title=See The Light, 
> media_artist=Ghost, 
> media_album_name=Prequelle, 
> app_id=2DB7CC49, 
> app_name=YouTube Music, 
> friendly_name=Entryway speaker, entity_picture=https://i.ytimg.com/vi/uDx4HR3o59A/hqdefault.jpg, 
> supported_features=21437,

@Andoramb This one's album cover appeared correctly in the module? Artist's, album and the other information appeared while the song was playing, right?

**Comment by Andoramb** [comment]
I'm going to close this for now, as it happens randomly... :)
Anyway, thanks for looking into this.

**Comment by ferferga** [comment]
@Andoramb Yeah, if you are not capable of seeing the images in the Google Home app as well as you described many times, this seems more likely an app issue and not an API change in Google Cast.

I don't have my mirror at a hand at the moment, but once I have it again, I will check it so we stay in the safe side.

Thank you very much for all your feedback!
