### ISSUE TITLE
Hide when not playing?

### ISSUE THREAD

**Issue by StefanMeGit** [ferferga/MMM-GoogleCast#2]
AWESOME WORK! Works flawless! 

Is it possible to add some option to hide the player when no music is playing? 

I have 3 of them and one "global" device when I play on all devices the same time...

-Kitchen
-LivingRoom
-ect.
-Apartment

Would be cool if u can stack them... if only kitchen is playing, show only kitchen. When apartment is playing, it only shows apartment ect.

**Comment by ferferga** [comment]
Good afternoon!

Thank you, it's great to see that you are enjoying this module!
Hiding the module when some device is not playing should be pretty straightforward and simple, so I don't see why I can't implement this :). I'm still mounting my mirror (wanted to do first the software side and prepare all the modules before packing all the hardware together), as well as working in other projects, so I want to finish them first and then make sure that everything works flawlessly (although it's a pretty straightforward change, I want to have the peace of mind that it works well =D). Should take a while (not much), but take for granted that I will make it :).

BTW, so you say that you are running multiple instances in parallel in the mirror? I didn't have the chance to properly test that, as I don't have many Google Cast devices around to test. would be great if you can confirm me that many instances of the modules are working well together!

Have a nice day!

**Comment by ferferga** [comment]
Closing, as this has been finally implemented in MMM-GoogleCast 2.0.

See the changelog and instructions for updating your installation in the [Releases](https://github.com/ferferga/MMM-GoogleCast/releases/tag/2.0) tab.
