### ISSUE TITLE
Spining loading on Magic Mirror OS

### ISSUE THREAD

**Issue by julianCast** [ferferga/MMM-GoogleCast#20]
I've notice you have another closed issue like [this](https://github.com/ferferga/MMM-GoogleCast/issues/7).

Important to notice I'm using **[Magic Mirror OS](https://github.com/guysoft/MagicMirrorOS)**.
My case: I have an updated version of your rep but still loading. How can I see the logs? I see in the js console: `Starting module: MMM-GoogleCast` By the way, no matter if a set hide true or false.

```
{
     module: 'MMM-GoogleCast',
     position: "bottom_right",
     classes: "default everyone",
     header: "Google Cast",
      config: {
          device: "1ef3eb8b-2fc0-c545-3ab5-1d8f05941f0c",
          hide: true
       }
 }
```

```
Scanning Google Cast devices inside your network...
DEVICE 0
--------------------
Name: Android TV
Type: cast
ID: 3709dd5b-8fe9-60be-c64b-56f7f41ce200
--------------------
DEVICE 1
--------------------
Name: Bathroom
Type: audio
ID: c8cf6e8e-0476-d7e8-5ef8-1d045508b6b4
--------------------
DEVICE 2
--------------------
Name: Kitchen speaker
Type: audio
ID: 9c0ad0e7-d80b-dd80-d5fb-74ddadcf9618
--------------------
DEVICE 3
--------------------
Name: All speakers
Type: group
ID: 1d79e17e-d916-4bba-a583-7f83a9b2f9e3
--------------------
DEVICE 4
--------------------
Name: House
Type: group
ID: bbed4608-5e12-4382-9589-6bcfb0a41bca
--------------------
DEVICE 5
--------------------
Name: JJ
Type: audio
ID: 2da61eef-514a-c675-0aaf-ac13c78a9f5f
--------------------
DEVICE 6
--------------------
Name: Living Room speaker
Type: cast
ID: 1ef3eb8b-2fc0-c545-3ab5-1d8f05941f0c
--------------------

```

Thank you!

**Comment by ferferga** [comment]
Hello @julianCast!

The output of the module can be seen when issuing MagicMirror with the ``npm start`` command - not sure how that's done in MagicMirror OS, first time I hear about it. Try to get all the debug output from MagicMirror and paste it here if you are unable to understand it. Unless some weird issue caused the dependencies not to update, something else is happening here

Hide only works when there is no media playing. In the initialization phase (which you can't get past to), it doesn't do anything.

**Comment by julianCast** [comment]
```
[2020-05-31 18:36:38.920] [ERROR]  Error: spawn python3 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn python3',
  path: 'python3',
  spawnargs: [
    'modules/MMM-GoogleCast/lib/Cast.py',
    '{"device":"bbed4608-5e12-4382-9589-6bcfb0a41bca","hide":true,"animationSpeed":3000,"showDeviceStatus":true,"showAlbumArtist":true}'
  ]
}
```

**Comment by ferferga** [comment]
@julianCast do you have python3 in your system?

**Comment by julianCast** [comment]
@ferferga `Python 2.7.16`

**Comment by ferferga** [comment]
@julianCast You need Python3, as specified in the install instructions.

Python 2 no longer has support, so you should stop using it.

**Comment by julianCast** [comment]
I already did the command, actually if I do` sudo apt install python3` again I get  `python3 is already the newest version (3.7.3-1).`. 
If I do :
` python -V` => `Python 2.7.16`
` python3 -V` => `Python 3.7.3`

**Comment by julianCast** [comment]
Any idea what's happening here?

**Comment by ferferga** [comment]
@julianCast What happens if you run ``which python3`` and set the path in the pythonPath key [here](https://github.com/ferferga/MMM-GoogleCast/blob/351817b1b453ca4e8bb8db30770ddc75d9ebc40b/node_helper.js#L11)?

**Comment by julianCast** [comment]
Before the change => Error: spawn **python3** ENOENT
After the change    => Error: spawn **/usr/bin/python3** ENOENT
```
[2020-06-08 13:32:14.574] [ERROR]  Error: spawn /usr/bin/python3 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /usr/bin/python3',
  path: '/usr/bin/python3',
  spawnargs: [
    'modules/MMM-GoogleCast/lib/Cast.py',
    '{"device":"bbed4608-5e12-4382-9589-6bcfb0a41bca","hide":true,"animationSpeed":3000,"showDeviceStatus":true,"showAlbumArtist":true}'
  ]
}
```

**Comment by ferferga** [comment]
@julianCast This is a MagicMirror OS specific issue. Can you ask there how you can expose other system apps to the MagicMirror process, so modules can use them? Afaik, they're using docker to run MagicMirror, so you just need to install python3 in the container as well (as you're running the which command in your host OS, instead of the container). However, each reboot you would need to repeat the install, so they must have a better way of setting how the container is created, so you can install the Python interpreter inside.

Post here the result so other users who might stumble across this know the solution 😊.

**Comment by julianCast** [comment]
That makes sense, I'll talk with them. Thanks!

**Comment by julianCast** [comment]
This is a posible solution, it implies building a custom container to install python 3 there.
https://github.com/guysoft/MagicMirrorOS/issues/14#issuecomment-640885075

Thank you @ferferga !
