### ISSUE TITLE
Spinning image

### ISSUE THREAD

**Issue by nikobix** [ferferga/MMM-GoogleCast#7]
Hi. I have run thorugh the setup as per the post but it seems I am not capturing any details from the casts.
I just get the spinning image.

Here are the details I have extracted as per your request.

Config.js details

                _{
                        module: 'MMM-GoogleCast',
                        position: "top_center",
                        classes: "default everyone",
                        header: "Google Cast",
                        config: {
                                device: "360acd12-cd8c-ff5c-7b67-7aa0262c3293",
                        }
                },_

Output from running  python3 GetChromecasts.py

pi@raspberrypi:~/MagicMirror/modules/MMM-GoogleCast $ python3 GetChromecasts.py

Scanning Google Cast devices inside your network...
DEVICE 0
--------------------
Name: Kitchen speaker
Type: audio
ID: 360acd12-cd8c-ff5c-7b67-7aa0262c3293
--------------------
DEVICE 1
--------------------
Name: home group
Type: group
ID: 72568aee-269c-459f-84b7-93014a0bb767
--------------------

Note the ID of the device do you want to integrate into your MagicMirror and put them inside config.js
Press ENTER to exit

and finally the log file that seems to get stuck at the Cast.py loaded succesfully.

[19:05:21.132] [LOG]    [MMM-GoogleCast] Update received! Details:
 { status: 'Loading MMM-GoogleCast Python backend...' }
[19:05:32.539] [LOG]    [MMM-GoogleCast] Update received! Details:
 { status: 'Cast.py loaded successfully' }

I left the log running for a long time, but still no progression.

MM seems to be running fine other than the GoogleCast.

It may be somthing I have done as a newbe!!

Any advice would be useful as this app is just what I want to see what is playing on our network.

Thanks

Nik

**Comment by ferferga** [comment]
Gooa afternoon! Did you try reloading the mirror and just after the 'Cast.py loaded succesfully', casting some content?

**Comment by nikobix** [comment]
Hi Fernando

Just carried out what you suggested. Closed MM and restarted with the logging.  Get to the same spinning image.
Log stopped again at the Cast.py loaded successfully, then I tried to cast to the group I had chosen. Still the same.

What should I expect to see once the Cast.py has loaded or is there a way to view a log of the Cast.py program to see if that has caused a error.

I had a similar issue with the spotify module, only to find out I was connecting to the PI via another PC and could not see any pop ups. 

This time I am on the PI it self.

Thanks

**Comment by nikobix** [comment]
Just as a side note, I see in the Cast Python program there are some commented out debug text. would it help me understand the issue if I un-commented these to see if there are any debug errors in the log file?

**Comment by nikobix** [comment]
mmm that just through an exception. 
Not an expert on Python. As they say a little knowledge is dangerous. :)

**Comment by ferferga** [comment]
@nikobix Those lines are useless and I think Python 2 only, it was my fault adding them and not removing it afterwards.

Just to make sure, your network doesn't have any kind of strange configuration like AP isolation or so on, right? It just has the standard network config for a house, right? Or did you perforn any relevant changes?

**Comment by nikobix** [comment]
no its a standard setup, although i do have a wifi repeater with a different ssid.  mmm perhaps i should change the wifi node i am connected to.

will let you know.

thanks

**Comment by nikobix** [comment]
Ah ha. Ok switched to my main Wifi router. When I restart MM I now get an unknown error on the Google Cast.
I reloaded the files, as I may have deleted something when I was playing with the debug, but still get the same error.
"There was an unknown error. Try to reboot your mirror."

Looking at the log I now get Device \'xxxxxx' not found or unreachable.
I ran the python3 GetChromecasts.py again to double check I still have the right device ID.

Funny how it will see the device ID in the Get Chormecasts, but not find it in the MMM-GoogleCast
 module.

I also tried with the other device I have and get the same error in the logs.

Very strange

**Comment by ferferga** [comment]
@nikobix so this seems really strange. Let me give you a bit of background:

pyChromecast (the library used by MMM-GoogleCast for connecting to cast devices) will always attempt to reconnect to the Google Cast device that it has connected whenever the connection is lost. While building my mirror and developing this module, I tested it and it worked flawlessly, even after an hour. This took place in my main residence, where I have a full-blown router and connection. However, I never intended my mirror to be there. Instead, it is in another house, where the connection is poor and the router is a portable one.
I did experience (during all the summer holidays) many problems having an stable connection between my portable router and my mirror, and 95% of the time, MMM-GoogleCast was able to resync again, but it's true that sometimes it didn't, so back then I was aware that I should implement some fallback in case the pyChromecast loop that handles events dies.

This weekend I've been in the house where my mirror is located (lucky you! 😉),and I also installed and configured a full-blown router I bought during the holidays for replacing my shitty hotspot, so I could also make some tests for trying to understand your issue. After all this process, I reached the following conclusions:

First of all, I thought that your issue might be caused to a change in the API that broke my module. However, after plugging my Chromecast Audio and Google Home and updating the, everything worked flawlessly. So, that made me wonder the following: **Is your device a Google one or is a cast-enabled from another manufacturer (JBL, Harman Kardon, etc...)**. It should work fine with those devices, but I didn't test anything else than Google devices, and third-party devices might have a non-standard implementation.

Second, I would like you to update pyChromecast. I saw that pyChromecast launched some updates that fixed some connection and reconnection problems. Could you run `pip install -U pychromecast`, reboot your mirror and see what happens?

If running the command doesn't solve anything, I suppose that the only solution for you is to wait until I add the connection fallbacks that I mentioned before. Even if that's not the cause of your issue, I will do it in the next version, as I already had it in my to-do list whenever I have some spare time after the exams, as the way the event loop is implemented in my backend is really dirty.

Please, tell me how it goes!
Have a nice day!

**Comment by ferferga** [comment]
@nikobix Any update about this?

**Comment by nikobix** [comment]
Hi Fernando

Not had a chance over the last week to work on the MM. I only have Google devices that I use for casting.

Will check the updates later today for pyChromecast and let you know.

Thanks

**Comment by nikobix** [comment]
OK did a bit more digging and it may be something to do with the pyChromecast. I ran through some tests directly with pyChromecast and it seems to hang on the wait() command.

I will check his issues page to see if there is something similar.

Will let you know.

Thanks

Nik

**Comment by nikobix** [comment]
Hi Fernando

Fixed it. 

It was to do with zeroconf call from pyChromecast. Found it on the pyChromecast Issues tab.

Just reverted to an earlier version and bang its working.

I ran 
pip3 install zeroconf==0.24.3

Nice work.

Thanks

**Comment by ferferga** [comment]
@nikobix Glad it worked and thanks for your feedback, it's great to see that you're enjoying it!

Could you link me to the issue where you found this, please? Maybe I can do something about it as well anyway 😁.

Have a nice day!

**Comment by nikobix** [comment]
This is the GIT Hub link, not sure how to link you in though. New to GIT Hub.
https://github.com/balloob/pychromecast/issues/332

**Comment by ferferga** [comment]
Thank you very much, yeah, I can access it just fine with the way you linked it. I will see if I can help them fix the problem after finishing exams (if they don't do that before).

I've already pushed some changes to MMM-GoogleCast as a workaround, so no newcomers will face your same issue right now. Thank you very much for doing the research as well, with no error reported in the logs (as pyChromecast did in fact detect your device, but wasn't able to conncet to it) it would've been really difficult.

Welcome to this great platform as well! It's very difficult to understand when you're a newbie, but as long as you keep discovering what it provides, you will realise how powerful it is.

Have a nice day!

**Comment by ferferga** [comment]
Finally fixed in balloob/pychromecast#337 , so I will revert back the changes I did for fixing the dependencies.
